language: java
jdk: openjdk11
env:
  global:
    - secure: RVAunGLaxPqAB9GYbN9auoKOHhU0LJHG2Z9BsN0gIP5oXPc11CrCLPnJYjfpPEKP04Jenl11OxB2fHvjYWIHcSIPl7U0VW5aoorwjLP0HmywO8AWmNvttRIm1JCYKyGfN4LPjBArXXXsS962DHaNosP6lteCew/SrwvWlCetEFEzXcEFMtxMTvu8sRryMOUFVW7yWPnns2NlNHNh+JEmMgZYLnXwsiKYgMLf/chxXaRbE9uctn9czFVlFMEwIQ7fIFtd7stMPUWzODO/4RSzXSwtzrnKiO3a5W3M1C0lULKQHsRr4/f9kOxHdjKfHvwgN65RSiDB5A1W9K8mnRIGUisOuVjv3uKB78b6baFqJo6dXA25M+RJUpmhihvjTCWH6R8TCfp60x9JGEKHJsAyrJOI/F/c4CIUkzhwtLusZchtpMCoyKxqxk5nL9UVQzkVeKOTams+VFc7K9EecMPZK7CcOXXvI8XuSJTUEE63a5QSJVIXLG8pO3KWvaR/10ST3IxROUGKaqOPVpaTP0mep/vosTlRcrVA+S9sY3/HoulQILygXomemZRimuHD8mRS4ZU1cQSikkVWEjs8wnFcitIzFkUgFi+GqRSW2aUA3gwH/hftGVBixvuZ2Apb13tFDelmKa+K8BLuXz31MlTnVaxoYfgzVaOKKV99ctX4MhY=
    - secure: LnbSWRVZpSuROA2vUAhTj2JXdxEl3aBVbI9fh1ndkYhddUnxc0bHizPviL0Q+HJeDer6OYgQXgkXvmAKlhQXAvQmygvkfFfUEPtzabOPmwA/R1JR+CIEZFSsjLbovY99pmlonG/AWR7ehFM3lUHPJx+VC8coHU7skUjGw/0aDkVCvM0VU86XuP4Zbnrs5xEe1MBKi/iYm1pjmcFkeEAk/wBRsMDMPj4I3VxZyTJslsoPyuH0axf0Rn6degi7j25sfp8ezN+Arfrp/pjSTUM6e6SN/Y89AtsA5BKJOE8gfyTMt5Szz4gviQg5mTzOy3ogwOXF+BNLe3/IL58eadP4k2qJTeCKJDnthzu747xGikxP5rFOnsVKQrnE4sGSPh81+33H0DWV9imvYmcesfwtEy2Z17H/U29rMnEwvyNFQfri1zNZvT+/sDOBMwqrP741aNkEGJoIHXQtYxSqHwfmZYTeemARrSii8SVAGg1MduN+ccujraCsM0ev+6xAzSZB2N6OSAtEou4PHQLnDVx4o6lOdX8JZab3PAHoeijpy7MYcUfiJETo4j3yKVyfjUsbh9Jup+PLZX89rppPlYecQU21aZFtv2Vm/09mjrJdOOGM5T5S03023k0YS6+PnbQBrFSl9Ag8fbCH3KRsNbkLZ/kLRyE7pBVQNGIpREjTV+k=
    - secure: oAgEZ4/S1vhPZYNGf4BeScyWn+SuM+iYr+mPc3tCDqodpvFZEQTjCx6/1MlBmisBYk8AlnJ/373CXJW8xvBsmBVhR1+I1bhHQRKH09yRWWNLlJDa0Jy2aJK1Umpgp3EabnNwj40a/7xQSLlDvflfo68CoJA49zBuvThFf997MIsee8hmKfGH+tqD8nGE5luFC9bX+oFmbCv4UeB9b18yrqVxlt8XDEC4DTj7dPb/LBYeW8PlO8jXVdYjqmJK70ortmax9LM46r8fTLYcxyTdgvlRHHKv6/4dsno6NqAI9MeHlpy0hMPVYcsmxpMFNT++O9sk3O37HMvdtuXdCFL8873v7pH8i82JbKzRYZEHlxhaSbFcQRG52FNS8gMUn2VzeEaUf4EEYETIEVH+B7GkVcWSU1wBHbdRTzddu49lOxLsQ3/OCGRE09F5c0fCFc4tYaRYSjI5ukZEQMeV3ovrfdar0KRQ8a81/Ym59sNlloMW6OvHXgE0zhG6vrAjFqAeJ5o6QGfyvA5s8vyOt20v6EWu/OcN2VcdO8HR91NMIWxim1wtnMcOKrIX74ObyydIkIsYJVuAdBZq30Kga2I3YIsqTO8R05jLVTxd65yPUiA4Xn7O3THcTvWfaAy4ZndmwJ0rSWQOB7JY7ddlZzdPvzLhd2BR35T3t20DUdWbDSA=
    - secure: XHEGb8S9kXgR96mnadoNwa0Jhg2x64NfvLj7bpLFI6OpiIGSslN/0ZNi7o33JcAqLmdy/xPP/H47cTTtyBqB1SU/NwRQUd4AMdFsbRWN8tPziMS26WOMFfQgR5eAVTC62MzwIQbEYJ5BFBxSkBmBNCqyixV/rzglQb08cgJZb1gNyVH/ymnlxlRsSvWyCLuSLxnP8eTjkt4OLiwekxV4sJPdy7Z6TXqBluc29o84CJe7wJc4EpgjQiRw9rrQeShb26g9KOn983AXJUGSmMAR9XHkOiVdTi1ftBMIclPxGkJCwEiCH/uTtz90xXxqmAs/u1BnKNbDC0JxHVH/QwNSL49KCwIzmsNbLYGZl9sVbxUcil+qVraag5q0CUUHqVsuVzUpqwQO71hBSuUnp+nuTHQP22lB2J1/yCcpPNvp2Z0WGLJVlVNq6LGmbn92woGD3bWkjRGsqks0TnorNYE8G11k6Ih3+HBI/nLQB5FTDQOxYTzMXoDv3i45lVgfs64dsS/zO/4yQB89+LeAxhDyGOg+K5M9wfUbd0FyziSVxD0u7iqnHfowFyi7qZnS+INQeUr4lXcmaFwYRPslNYskJhv7JPszgu2qPiv57hp/sw4ZuwtDqVS0FYB4dLscrVhjeN+WstYc0u2FUBScQYoCuM4t4oQ/VsFfNF1ux4VoBYw=
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
deploy:
  provider: script
  script: ./gradlew publishAndRelease
    -PprojectVersion=$TRAVIS_TAG
    -Psigning.keyId=$SIGNING_KEY_ID
    -Psigning.password=
    -Psigning.secretKeyRingFile=key.gpg
    -Psonatype.username=$SONATYPE_USERNAME
    -Psonatype.password=$SONATYPE_PASSWORD
  skip_cleanup: true
  on:
    tags: true
before_deploy:
  - openssl aes-256-cbc -K $encrypted_2e6b62dd1b86_key -iv $encrypted_2e6b62dd1b86_iv -in key.gpg.enc -out key.gpg -d
