#!/bin/sh
basedir=$(PWD)/$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
PATH=$PATH:$basedir/../../nodejs/node-v12.4.0-win-x64
$basedir/../../nodejs/node-v12.4.0-win-x64/node "$basedir/../../nodejs/node-v12.4.0-win-x64/node_modules/npm/bin/npm-cli.js" $* --scripts-prepend-node-path=auto
